### ISSUE TITLE
客制化的第一步✔［提醒苏苏✘］

### ISSUE THREAD

**Issue by Glandoll** [iirose-tools/YakumoRan#65]
需要自定义欢迎词库！
不需要《呐喊》✘

**Comment by TheresaQWQ** [comment]
暂时没想好怎么做，扔配置文件的话配置文件就太长了

**Comment by TheresaQWQ** [comment]
有想法了，不写配置文件，写数据文件里面就行了

**Comment by TheresaQWQ** [comment]
在2.0中实现了完整的自定义功能，参考仓库 [iirose-tools/YakumoRan-Common](https://github.com/iirose-tools/YakumoRan-Common)
