### ISSUE TITLE
更换房间bug

### ISSUE THREAD

**Issue by BSTluo** [iirose-tools/YakumoRan#8]
更换房间时会发生一些错误
![image](https://user-images.githubusercontent.com/36332288/114407694-40aaa380-9bdb-11eb-829a-4c7bea39ccb0.png)
然后bot无限重启（？）
![image](https://user-images.githubusercontent.com/36332288/114407797-5d46db80-9bdb-11eb-8a6c-0a9adf7ac117.png)

**Comment by TheresaQWQ** [comment]
周末看看

**Comment by TheresaQWQ** [comment]
无法复现
